# MBP_S1

In [1]:
import pymysql
from sqlalchemy import create_engine
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv('/Users/AFROARC/Documents/GitHub/Data Sets/regression_data.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21596 entries, 0 to 21595
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   7129300520  21596 non-null  int64
 1   10/13/14    21596 non-null  object
 2   3           21596 non-null  int64
 3   1           21596 non-null  float64
 4   1180        21596 non-null  int64
 5   5650        21596 non-null  int64
 6   1.1         21596 non-null  float64
 7   0           21596 non-null  int64
 8   0.1         21596 non-null  int64
 9   3.1         21596 non-null  int64
 10  7           21596 non-null  int64
 11  1180.1      21596 non-null  int64
 12  0.2         21596 non-null  int64
 13  1955        21596 non-null  int64
 14  0.3         21596 non-null  int64
 15  98178       21596 non-null  int64
 16  47.5112     21596 non-null  float64
 17  -122.257    21596 non-null  float64
 18  1340        21596 non-null  int64
 19  5650.1      21596 non-null  int64
 20  221900      21596 non-null  int64
dtypes: float64(4), int64(16), object(1)
memory usage: 3.5+ MB

In [4]:
df.isna().sum()

7129300520    0
10/13/14      0
3             0
1             0
1180          0
5650          0
1.1           0
0             0
0.1           0
3.1           0
7             0
1180.1        0
0.2           0
1955          0
0.3           0
98178         0
47.5112       0
-122.257      0
1340          0
5650.1        0
221900        0
dtype: int64

In [6]:
df.describe()

,7129300520,3,1,1180,5650,1.1,0,0.1,3.1,7,1180.1,0.2,1955,0.3,98178,47.5112,-122.257,1340,5650.1,221900
count,2.159600e+04,21596.000000,21596.000000,21596.00000,2.159600e+04,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,21596.000000,2.159600e+04
mean,4.580356e+09,3.373217,2.115878,2080.36354,1.509985e+04,1.494119,0.007548,0.234303,3.409844,7.657946,1788.625023,291.738516,1971.000417,84.468698,98077.947212,47.560095,-122.213981,1986.650259,12758.612660,5.403113e+05
std,2.876750e+09,0.926317,0.768965,918.10694,4.141355e+04,0.539685,0.086551,0.766406,0.650555,1.173218,827.768566,442.673598,29.375712,401.830330,53.509980,0.138555,0.140726,685.232209,27275.030548,3.673703e+05
min,1.000102e+06,1.000000,0.500000,370.00000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,3.000000,370.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000,7.800000e+04
25%,2.123049e+09,3.000000,1.750000,1430.00000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471100,-122.328000,1490.000000,5100.000000,3.220000e+05
50%,3.904930e+09,3.000000,2.250000,1910.00000,7.619000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.231000,1840.000000,7620.000000,4.500000e+05
75%,7.308950e+09,4.000000,2.500000,2550.00000,1.068550e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000,6.450000e+05
max,9.900000e+09,33.000000,8.000000,13540.00000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000,7.700000e+06